In [1]:
import pandas as pd
data = pd.read_csv('data_for_analisis.csv')

In [2]:
data.head()

,kd_sekolah,pendidikan_sederajat,jenis_sek,sts_sek,kurikulum,daerah_khusus,kd_kokab,wilayah_bagian,jenis_wilayah,status_wilayah,...,SMK_PIM,SMK_SARPR,SMK_TEFA,TAS,TOC,TOR,TSC,WEL,SES_sekolah,IASP
0,8500033,SMA/SMK/MA,Paket C,N,Kurikulum Merdeka,Tidak,190,Indonesia Barat,KOTA,URBAN,...,NaN,NaN,NaN,50.0593,NaN,85.6038,59.4229,NaN,77.91,84.51
1,8500033,SMA/SMK/MA,Paket C,N,Kurikulum Merdeka,Tidak,190,Indonesia Barat,KOTA,URBAN,...,NaN,NaN,NaN,49.9407,43.2139,NaN,NaN,24.9123,77.91,84.51
2,8500033,SMA/SMK/MA,Paket C,N,Kurikulum Merdeka,Tidak,190,Indonesia Barat,KOTA,URBAN,...,NaN,NaN,NaN,61.4472,NaN,68.7922,64.9234,40.1754,77.91,84.51
3,8500033,SMA/SMK/MA,Paket C,N,Kurikulum Merdeka,Tidak,190,Indonesia Barat,KOTA,URBAN,...,NaN,NaN,NaN,NaN,64.9295,NaN,68.1695,66.4912,77.91,84.51
4,8500033,SMA/SMK/MA,Paket C,N,Kurikulum Merdeka,Tidak,190,Indonesia Barat,KOTA,URBAN,...,NaN,NaN,NaN,NaN,NaN,62.1256,NaN,NaN,77.91,84.51

### Aggregasi Kolom Nilai AN

In [3]:
kolom_nilai = [
    'LIT', 'LIT_INF', 'LIT_SAS', 'LIT_L1', 'LIT_L2', 'LIT_L3',
    'NUM', 'NUM_ALJ', 'NUM_GEO', 'NUM_BIL', 'NUM_DAT', 'NUM_L1', 'NUM_L2', 'NUM_L3'
]

data['nilai_AN'] = data[kolom_nilai].mean(axis=1)
data[['nilai_AN'] + kolom_nilai].head()

,nilai_AN,LIT,LIT_INF,LIT_SAS,LIT_L1,LIT_L2,LIT_L3,NUM,NUM_ALJ,NUM_GEO,NUM_BIL,NUM_DAT,NUM_L1,NUM_L2,NUM_L3
0,63.664286,58.83,60.50,56.83,63.50,59.00,44.49,69.66,68.00,75.17,64.50,71.83,72.00,72.50,54.49
1,44.385000,42.83,41.33,44.66,23.32,48.49,46.49,49.99,27.66,68.33,43.49,34.16,44.99,51.16,54.49
2,48.612143,53.33,57.33,45.83,54.33,40.99,72.67,48.99,56.16,42.16,69.16,9.65,40.49,60.66,28.82
3,65.330000,79.33,69.00,89.17,85.17,81.83,47.16,59.50,57.16,52.99,72.83,40.99,53.33,58.33,67.83
4,87.857143,100.00,100.00,99.67,93.67,100.00,100.00,79.17,79.17,78.67,84.33,71.33,100.00,62.66,81.33

### Drop Kolom tidak terpakai

In [4]:
kolom_di_drop = [
    'SES_siswa',
    'LIT',
    'LIT_INF',
    'LIT_SAS',
    'LIT_L1',
    'LIT_L2',
    'LIT_L3',
    'NUM',
    'NUM_ALJ',
    'NUM_GEO',
    'NUM_BIL',
    'NUM_DAT',
    'NUM_L1',
    'NUM_L2',
    'NUM_L3',
    'AAKN',
    'AAMN',
    'AAPR',
    'ABKR',
    'ABMK',
    'AMKA',
    'AMKB',
    'AMKG',
    'AMTA',
    'AMTB',
    'GRKP',
    'GRPB',
    'GRPR',
    'KGKI',
    'KGMB',
    'KMPE',
    'KMPR',
    'KRBB',
    'KRMI',
    'KRMK',
    'NKAE',
    'NKPI',
    'NKRE',
    'ACH',
    'AIN',
    'AKC',
    'BCP',
    'BUL',
    'CAF',
    'DIB',
    'DIC',
    'DIE',
    'ECP',
    'ENP',
    'EQC',
    'EQR',
    'ESA',
    'ESV',
    'ISB',
    'ITB',
    'KKG',
    'OCC',
    'PBR',
    'PBU',
    'PCP',
    'PKG',
    'PLIT',
    'PMU',
    'PNUM',
    'POT',
    'PSA',
    'PSV',
    'RKG',
    'RPI',
    'SAF',
    'SBU',
    'SKG',
    'SMK_GRMAG',
    'SMK_GTINS',
    'SMK_INDS',
    'SMK_PBEL',
    'SMK_PIM',
    'SMK_SARPR',
    'SMK_TEFA',
    'TAS',
    'TOC',
    'TOR',
    'TSC',
    'WEL',
    'SES_sekolah',
    'IASP',
    'pendidikan_sederajat',
    'jenis_sek',
    'sts_sek',
    'kd_kokab'
]

data = data.drop(columns=kolom_di_drop)
display(data.tail(5))

,kd_sekolah,kurikulum,daerah_khusus,wilayah_bagian,jenis_wilayah,status_wilayah,proporsi_pendidik_min_s1,proporsi_pendidik_sertifikasi,jumlah_peserta_didik,jumlah_pendidik,...,"Kepemilikan buku-buku tentang seni, musik, atau desain","Kepemilikan buku-buku tentang bahasa, termasuk kamus",Kepemilikan buku-buku yang bisa membantumu mengerjakan tugas-tugas sekolah,Kepemilikan televisi layar datar,Kepemilikan mobil,Kepemilikan Pendingin Ruangan (AC),"Kepemilikan telepon seluler (handphone) dengan akses internet (misal, smartphone)",Kepemilikan komputer tablet (Tab/iPad),Kpemilikan karya-karya seni (misal: lukisan/patung seni),nilai_AN
48055,5100130,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,22.222222,119.0,9.0,...,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Satu,Tidak ada,Satu,Satu,Tidak ada,Tidak ada,38.992143
48056,5100130,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,22.222222,119.0,9.0,...,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Satu,Tidak ada,Tidak ada,Satu,Tidak ada,Tidak ada,54.864286
48057,5100130,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,22.222222,119.0,9.0,...,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Satu,Tidak ada,Tidak ada,Tiga atau lebih,Tidak ada,Tiga atau lebih,42.576429
48058,5100130,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,22.222222,119.0,9.0,...,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Tiga atau lebih,Tiga atau lebih,Tiga atau lebih,Tiga atau lebih,Tiga atau lebih,Tiga atau lebih,47.505000
48059,5100130,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,22.222222,119.0,9.0,...,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Tidak ada,Tidak ada,Tidak ada,Satu,Tidak ada,Tidak ada,41.956429

### Clean NaN

Jumlah NAN

In [5]:
data.isna().sum()

kd_sekolah                                                                                           0
kurikulum                                                                                         6852
daerah_khusus                                                                                        0
wilayah_bagian                                                                                       0
jenis_wilayah                                                                                        0
status_wilayah                                                                                       0
proporsi_pendidik_min_s1                                                                          6852
proporsi_pendidik_sertifikasi                                                                     6852
jumlah_peserta_didik                                                                              6852
jumlah_pendidik                                                                                   6852
rasio_pendidik_peserta_didik                                                                      6852
jumlah_r_kelas                                                                                    6852
ketersediaan_internet                                                                             6852
ketersediaan_listrik                                                                              6852
jumlah_komp_milik                                                                                 6852
jumlah_perpus                                                                                     6852
jumlah_rombel                                                                                     6852
jumlah_siswa_rombel                                                                               6852
jumlah_siswa_penerima_PIP                                                                         6852
rasio_siswa_penerima_PIP                                                                          6852
kd_siswa_an                                                                                          0
Apakah kamu perempuan atau laki-laki?                                                                0
Ada berapa keluarga yang tinggal bersama di rumahmu?                                              5143
Apa jenjang sekolah tertinggi yang diselesaikan ayahmu?                                           5142
Apa jenjang sekolah tertinggi yang diselesaikan ibumu?                                            5148
Apa pekerjaan ayahmu?                                                                             5152
Apa pekerjaan ibumu?                                                                              5155
Kepemilikan Meja belajar di rumah                                                                21645
Kamar tidur untuk dirimu sendiri (tidak berbagi dengan saudara atau orang lain)                  21713
Tempat belajar yang tenang di rumah                                                              21796
Listrik dan lampu untuk belajar di rumah pada malam hari                                         21884
Komputer, laptop, atau tablet yang bisa kamu pakai untuk keperluan belajar atau tugas sekolah    21930
Kepemilikan perangkat lunak (software atau program komputer) pendidikan                          22012
Sambungan ke internet di rumah                                                                   22092
Kepemilikan alat baca buku digital (seperti Kindle, Kobo, dll)                                   22013
Kepemilikan buku-buku fiksi/sastra seperti novel, kumpulan cerpen, atau kumpulan puisi            5696
Kepemilikan buku-buku tentang sains atau teknologi                                                6283
Kepemilikan buku-buku tentang seni, musik, atau desain                                            6514
Kepemilikan buku-buku tentang bahasa, termasuk kamus                                              6518
Kepemilikan buku-buku yang bisa membantumu mengerjakan tugas-tugas sekolah                        6196
Kepemilikan televisi layar datar                                                                  5856
Kepemilikan mobil                                                                                 6378
Kepemilikan Pendingin Ruangan (AC)                                                                6846
Kepemilikan telepon seluler (handphone) dengan akses internet (misal, smartphone)                 6302
Kepemilikan komputer tablet (Tab/iPad)                                                            6820
Kpemilikan karya-karya seni (misal: lukisan/patung seni)                                          6285
nilai_AN                                                                                          3781
dtype: int64

In [6]:
data.dropna(inplace=True)

After Clean NAN

In [7]:
data.isna().sum()

kd_sekolah                                                                                       0
kurikulum                                                                                        0
daerah_khusus                                                                                    0
wilayah_bagian                                                                                   0
jenis_wilayah                                                                                    0
status_wilayah                                                                                   0
proporsi_pendidik_min_s1                                                                         0
proporsi_pendidik_sertifikasi                                                                    0
jumlah_peserta_didik                                                                             0
jumlah_pendidik                                                                                  0
rasio_pendidik_peserta_didik                                                                     0
jumlah_r_kelas                                                                                   0
ketersediaan_internet                                                                            0
ketersediaan_listrik                                                                             0
jumlah_komp_milik                                                                                0
jumlah_perpus                                                                                    0
jumlah_rombel                                                                                    0
jumlah_siswa_rombel                                                                              0
jumlah_siswa_penerima_PIP                                                                        0
rasio_siswa_penerima_PIP                                                                         0
kd_siswa_an                                                                                      0
Apakah kamu perempuan atau laki-laki?                                                            0
Ada berapa keluarga yang tinggal bersama di rumahmu?                                             0
Apa jenjang sekolah tertinggi yang diselesaikan ayahmu?                                          0
Apa jenjang sekolah tertinggi yang diselesaikan ibumu?                                           0
Apa pekerjaan ayahmu?                                                                            0
Apa pekerjaan ibumu?                                                                             0
Kepemilikan Meja belajar di rumah                                                                0
Kamar tidur untuk dirimu sendiri (tidak berbagi dengan saudara atau orang lain)                  0
Tempat belajar yang tenang di rumah                                                              0
Listrik dan lampu untuk belajar di rumah pada malam hari                                         0
Komputer, laptop, atau tablet yang bisa kamu pakai untuk keperluan belajar atau tugas sekolah    0
Kepemilikan perangkat lunak (software atau program komputer) pendidikan                          0
Sambungan ke internet di rumah                                                                   0
Kepemilikan alat baca buku digital (seperti Kindle, Kobo, dll)                                   0
Kepemilikan buku-buku fiksi/sastra seperti novel, kumpulan cerpen, atau kumpulan puisi           0
Kepemilikan buku-buku tentang sains atau teknologi                                               0
Kepemilikan buku-buku tentang seni, musik, atau desain                                           0
Kepemilikan buku-buku tentang bahasa, termasuk kamus                                             0
Kepemilikan buku-buku yang bisa membantumu mengerjakan tugas-tugas sekolah                       0
Kepemilikan televisi layar datar                                                                 0
Kepemilikan mobil                                                                                0
Kepemilikan Pendingin Ruangan (AC)                                                               0
Kepemilikan telepon seluler (handphone) dengan akses internet (misal, smartphone)                0
Kepemilikan komputer tablet (Tab/iPad)                                                           0
Kpemilikan karya-karya seni (misal: lukisan/patung seni)                                         0
nilai_AN                                                                                         0
dtype: int64

## Selesksi Data Indo timur

In [8]:
print(f'total Data =>',{data['kd_siswa_an'].count()})
data_timur = data[data['wilayah_bagian']=='Indonesia Timur']
print(f'data dari Indonesia Timur',{data_timur['kd_siswa_an'].count()})
data_timur.tail()

total Data => {19936}
data dari Indonesia Timur {2162}

,kd_sekolah,kurikulum,daerah_khusus,wilayah_bagian,jenis_wilayah,status_wilayah,proporsi_pendidik_min_s1,proporsi_pendidik_sertifikasi,jumlah_peserta_didik,jumlah_pendidik,...,"Kepemilikan buku-buku tentang seni, musik, atau desain","Kepemilikan buku-buku tentang bahasa, termasuk kamus",Kepemilikan buku-buku yang bisa membantumu mengerjakan tugas-tugas sekolah,Kepemilikan televisi layar datar,Kepemilikan mobil,Kepemilikan Pendingin Ruangan (AC),"Kepemilikan telepon seluler (handphone) dengan akses internet (misal, smartphone)",Kepemilikan komputer tablet (Tab/iPad),Kpemilikan karya-karya seni (misal: lukisan/patung seni),nilai_AN
47962,5100134,Kurikulum Merdeka,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,10.0,121.0,10.0,...,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Satu,Tidak ada,Tidak ada,Dua,Satu,Tiga atau lebih,28.681429
47964,5100134,Kurikulum Merdeka,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,10.0,121.0,10.0,...,Kira-kira 11-25 buku,Kira-kira 1-10 buku,Kira-kira lebih dari 100 buku,Dua,Satu,Tidak ada,Dua,Dua,Tiga atau lebih,42.539286
47965,5100134,Kurikulum Merdeka,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,10.0,121.0,10.0,...,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,36.646429
47967,5100134,Kurikulum Merdeka,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,10.0,121.0,10.0,...,Tidak ada,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,37.288571
47971,5100134,Kurikulum Merdeka,Tidak,Indonesia Timur,KABUPATEN,RURAL,100.0,10.0,121.0,10.0,...,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Kira-kira 1-10 buku,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,32.430714

Grouping Nilai AN

In [9]:
nilai_AN_min = data_timur['nilai_AN'].min()
nilai_AN_max = data_timur['nilai_AN'].max()
interval = (nilai_AN_max - nilai_AN_min) / 3
def klasifikasi_nilai_AN(x):
  if x < nilai_AN_min + interval:
      return 'rendah'
  elif x < nilai_AN_min + 2 * interval:
    return 'cukup'
  else:
    return 'tinggi'

data_timur['kelas_nilai_AN'] = data_timur['nilai_AN'].apply(klasifikasi_nilai_AN)
data_timur[['nilai_AN', 'kelas_nilai_AN']].head()

C:\Users\Michael Luwi Pallea\AppData\Local\Temp\ipykernel_22244\3235821301.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_timur['kelas_nilai_AN'] = data_timur['nilai_AN'].apply(klasifikasi_nilai_AN)

       nilai_AN kelas_nilai_AN
2515  40.552143         rendah
2516  45.932857         rendah
2518  52.375714          cukup
2519  40.957857         rendah
2521  47.171429          cukup

DATA TIMUR FINAL

In [10]:
data_timur = data_timur.drop('nilai_AN',axis=1)
data_timur.head()

,kd_sekolah,kurikulum,daerah_khusus,wilayah_bagian,jenis_wilayah,status_wilayah,proporsi_pendidik_min_s1,proporsi_pendidik_sertifikasi,jumlah_peserta_didik,jumlah_pendidik,...,"Kepemilikan buku-buku tentang seni, musik, atau desain","Kepemilikan buku-buku tentang bahasa, termasuk kamus",Kepemilikan buku-buku yang bisa membantumu mengerjakan tugas-tugas sekolah,Kepemilikan televisi layar datar,Kepemilikan mobil,Kepemilikan Pendingin Ruangan (AC),"Kepemilikan telepon seluler (handphone) dengan akses internet (misal, smartphone)",Kepemilikan komputer tablet (Tab/iPad),Kpemilikan karya-karya seni (misal: lukisan/patung seni),kelas_nilai_AN
2515,8500067,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,URBAN,100.0,0.0,94.0,5.0,...,Tidak ada,Tidak ada,Kira-kira 1-10 buku,Satu,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,rendah
2516,8500067,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,URBAN,100.0,0.0,94.0,5.0,...,Tidak ada,Kira-kira 11-25 buku,Kira-kira lebih dari 100 buku,Satu,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tiga atau lebih,rendah
2518,8500067,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,URBAN,100.0,0.0,94.0,5.0,...,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,Tidak ada,cukup
2519,8500067,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,URBAN,100.0,0.0,94.0,5.0,...,Tidak ada,Tidak ada,Kira-kira 1-10 buku,Satu,Tidak ada,Tidak ada,Tiga atau lebih,Tidak ada,Tidak ada,rendah
2521,8500067,Kurikulum 2013,Tidak,Indonesia Timur,KABUPATEN,URBAN,100.0,0.0,94.0,5.0,...,Tidak ada,Tidak ada,Kira-kira 1-10 buku,Satu,Tidak ada,Tidak ada,Dua,Tidak ada,Tidak ada,cukup

In [11]:
data_timur.to_csv('data_timur.csv')